### ISSUE TITLE
KeyError: 'inception_3c_3x3_conv1_w'

### ISSUE THREAD

**Issue by coderchintan** [soumik12345/Nearest-Celebrity-Face#1]
![Screenshot from 2019-04-12 15-35-44](https://user-images.githubusercontent.com/29311528/56029744-b653ae80-5d38-11e9-9375-e5db287343b2.png)

**Comment by soumik12345** [comment]
This program is not compatible with `python2`. Try installing the dependencies running with `python3`. Use `python` if you are on Windows.

**Comment by coderchintan** [comment]
I also tried with python3 but the same error is arised

**Comment by soumik12345** [comment]
This is because I removed some of the weights from the pre-trained models. If you want all the weights, please drop me an email at 19soumik.rakshit96@gmail.com and mention your purpose in details and I will send you a Google Drive link.
